AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  {{ cookiecutter.project_name }}

  SAM Template for {{ cookiecutter.project_name }}

Metadata:
  AWS::ServerlessRepo::Application:
    Name: {{ cookiecutter.project_name }}
    Description: SAM Template for {{ cookiecutter.project_name }}
    Author: {{ cookiecutter.author }}
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/scrambledeggs/{{ cookiecutter.project_name }}
    SourceCodeUrl: https://github.com/scrambledeggs/{{ cookiecutter.project_name }}
    SemanticVersion: 0.0.1

Parameters:
  DomainName:
    Type: String
  AppEnv:
    Type: String
    Default: "staging"
  DistributionId:
    Type: String
    Default: "NAKNANGPATATAS"
  AmzRegion:
    Type: String
  AmzAccountId:
    Type: String
  CorsAllowedHeaders:
    Type: String
    Default: "Access-Control-Allow-Headers,Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,X-Api-Key,x-api-key"
  CorsAllowedMethods:
    Type: String
    Default: "POST,GET,PUT,PATCH,DELETE,OPTIONS"
  CorsAllowedOrigins:
    Type: String
    Default: "*"
  Subnets:
    Type: String
  SecurityGroups:
    Type: String
  CertificateArnUs:
    Type: String
  CertificateArnAp:
    Type: String
  HostedZoneId:
    Type: String
  AuthorizerFunctionArn:
    Type: String

Conditions:
  ProdEnv: !Equals [!Ref AppEnv, "production"]
  NonProdEnv: !Not [!Equals [!Ref AppEnv, "production"]]

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active
    Tags:
      Usage: {{ cookiecutter.project_name }}
      Environment: !If [ProdEnv, prod, non-prod]
    PropagateTags: true
    VpcConfig:
      SecurityGroupIds: !Split [",", !Ref SecurityGroups]
      SubnetIds: !Split [",", !Ref Subnets]

    Timeout: 5
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

    Environment:
      Variables:
        APP_ENV: !Ref AppEnv
        CORS_ALLOWED_HEADERS: !Ref CorsAllowedHeaders
        CORS_ALLOWED_ORIGINS: !Ref CorsAllowedOrigins
        CORS_ALLOWED_METHODS: !Ref CorsAllowedMethods
        DISTRIBUTION_ID: !Ref DistributionId
        AMZ_REGION: !Ref AmzRegion
        AMZ_ACCOUNT_ID: !Ref AmzAccountId
  Api:
    TracingEnabled: true
    Cors:
      AllowHeaders: !Join ["", ["'", !Ref CorsAllowedHeaders, "'"]]
      AllowMethods: !Join ["", ["'", !Ref CorsAllowedMethods, "'"]]
      AllowOrigin: !Join ["", ["'", !Ref CorsAllowedOrigins, "'"]]

Resources:
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Tags:
        Usage: {{ cookiecutter.project_name }}
        Environment: !If [ProdEnv, prod, non-prod]
      StageName: !Ref AppEnv
      GatewayResponses:
        DEFAULT_4xx:
          ResponseParameters:
            Headers:
              Access-Control-Expose-Headers: "'WWW-Authenticate'"
              Access-Control-Allow-Origin:
                !Join ["", ["'", !Ref CorsAllowedOrigins, "'"]]
      Auth:
        DefaultAuthorizer: ApiKeyAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          ApiKeyAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !Ref AuthorizerFunctionArn
            Identity:
              Headers:
                - x-api-key
                - x-user-token
                - Authorizer
              ReauthorizeEvery: 0

  ApiDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    DependsOn:
      - ApiGateway
    Properties:
      DomainName: !Ref DomainName
      DomainNameConfigurations:
        - CertificateArn: !Ref CertificateArnAp
          EndpointType: REGIONAL

  ApiGatewayMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref ApiGateway
      DomainName: !Ref ApiDomainName
      Stage: !Ref AppEnv

  CachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: {{ cookiecutter.camelcase_project_name }}CachePolicy
        DefaultTTL: 86400
        MaxTTL: 86400
        MinTTL: 1
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Origin
              - x-user-token
              - X-User-Token
              - x-api-key
              - X-Api-Key
              - Authorizer
              - authorizer
          QueryStringsConfig:
            QueryStringBehavior: all
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArnUs
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: ServerlessRestApi
          CachePolicyId: !Ref CachePolicy
          Compress: true
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - POST
            - PUT
            - DELETE
            - PATCH # Added all methods
          CachedMethods:
            - GET
            - HEAD # Cache GET and HEAD methods only
        Origins:
          - Id: ServerlessRestApi
            DomainName: !Sub "${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com"
            OriginPath: !Sub "/${AppEnv}"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only

  Route53RecordNonProd:
    Type: AWS::Route53::RecordSet
    Condition: NonProdEnv
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront Hosted Zone ID (static)
        DNSName: !GetAtt CloudFrontDistribution.DomainName

  AllEndpoints:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handlers/AllEndpoints
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /endpoints
            Method: GET
            RestApiId: !Ref ApiGateway
            Auth:
              Authorizer: NONE

  HelloWorldV1:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handlers/HelloWorldV1
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/hello-world
            Method: GET
            RestApiId: !Ref ApiGateway
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM_1: VALUE

  CachedWorldV1:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handlers/CachedWorldV1
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/cached-world
            Method: GET
            RestApiId: !Ref ApiGateway
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM_1: ANOTHER_VALUE

  InvalidateCachedWorldV1:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handlers/InvalidateCachedWorldV1
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/invalidate-cached-world
            Method: POST
            RestApiId: !Ref ApiGateway
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DISTRIBUTION_ID: !Ref DistributionId # TODO: Find a way to get !Ref CloudFrontDistribution (CloudFrontDistributionID) without circular dependency
      Policies:
        - CloudFrontFullAccess
    # DependsOn: CloudFrontDistribution # TODO: This could help on CloudFrontDistributionID

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CloudFrontDistributionId:
    Description: "CloudFront Distribution ID"
    Value: !Ref CloudFrontDistribution
  ApiGatewayURL:
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${AppEnv}/"
  CloudfrontDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Join ["-", [!Ref AppEnv, {{ cookiecutter.service_name }}, "CloudfrontDomainName"]]
